---
output: 
  html_document:
    code_folding: hide
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(patchwork)
```

```{r include=FALSE}
list.files(path = "/courses/EDS214/nutria/raw-data")

bq1 <- read_csv("/courses/EDS214/nutria/raw-data/QuebradaCuenca1-Bisley.csv", na = c("-9999", "-9999.00"))
bq2 <- read_csv("/courses/EDS214/nutria/raw-data/QuebradaCuenca2-Bisley.csv", na = c("-9999", "-9999.00")) %>% 
  separate(col = Sample_Date, into = c("Sample_Date", "time"), sep = " ") %>% 
  select(-time)
bq3 <- read_csv("/courses/EDS214/nutria/raw-data/QuebradaCuenca3-Bisley.csv", na = c("-9999", "-9999.00"))
prm <- read_csv("/courses/EDS214/nutria/raw-data/RioMameyesPuenteRoto.csv", na = c("-9999", "-9999.00"))

stream_data <- rbind(bq1, bq2, bq3, prm) %>% 
  clean_names() %>% 
  select(sample_id, sample_date, no3, k) %>% 
  mutate(sample_date = mdy(sample_date))
```

```{r include=FALSE}
plot_k <- ggplot(data = stream_data, aes(x = sample_date, y = k / 2)) +
  geom_line(aes(linetype = sample_id)) +
  geom_vline(xintercept = as.Date("1989-10-01"), 
             linetype = "dashed") +
  scale_x_date(limits = c(as.Date("1989-01-01"), 
                          as.Date("1994-07-01")), 
               date_breaks = "1 year", 
               date_labels = "%Y", 
               position = "top") +
  labs(x = "Year", 
       y = "K mg l\u207b\u00b9",
       linetype = "")  +
  theme_classic() +
  theme(#axis.text.x = element_blank(),
        #axis.title.x = element_blank(),
        legend.position = c(0.9,0.4),
        panel.border = element_rect(fill = NA, size = 1))
```

```{r include=FALSE}
plot_no3 <- ggplot(data = stream_data, aes(x = sample_date, y = no3 / 3)) +
  geom_line(aes(linetype = sample_id), show.legend = FALSE) +
  geom_vline(xintercept = as.Date("1989-10-01"), 
             linetype = "dashed") +
  scale_x_date(limits = c(as.Date("1989-01-01"), 
                          as.Date("1994-07-01")), 
               date_breaks = "1 year", 
               date_labels = "%Y") +
  labs(x = "Year", 
      y = "NO\u2083\u2010N \u00b5g l\u207b\u00b9") +
  theme_classic() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        panel.border = element_rect(fill = NA, size = 1))

```

```{r}
plot_combo <- plot_k / plot_no3 

plot_combo
```

